[[dotfiles]]
original = "~/.config/starship.toml"
copy = "./starship.toml"

[[dotfiles]]
original = "~/.config/wezterm"
copy = "./wezterm"

[[dotfiles]]
original = "~/.config/alacritty"
copy = "./alacritty"

[[dotfiles]]
original = "~/.config/winfetch"
copy = "./winfetch"

[[dotfiles]]
original = "~/Documents/PowerShell"
copy = "./pwsh"

[[dotfiles]]
original = "~/Documents/devs/projects/.clang-format"
copy = "./.clang-format"

[[dotfiles]]
original = "~/.config/nvim"
copy = "./nvim"

[[dotfiles]]
original = "~/.config/yazi"
copy = "./yazi"


