[package]
name = "df"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
fs_extra = "1.2.0"
